/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateTemplateDto,
  CreateUniversityDto,
  PatchCompanyAdminDto,
  PatchTemplateDto,
  SeedSuperadminDto,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const adminControllerOverview = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/overview`,
    method: "GET",
    signal,
  });
};

export const getAdminControllerOverviewQueryKey = () => {
  return [`/api/admin/overview`] as const;
};

export const getAdminControllerOverviewQueryOptions = <
  TData = Awaited<ReturnType<typeof adminControllerOverview>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof adminControllerOverview>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminControllerOverviewQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminControllerOverview>>
  > = ({ signal }) => adminControllerOverview(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminControllerOverview>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminControllerOverviewQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerOverview>>
>;
export type AdminControllerOverviewQueryError = unknown;

export function useAdminControllerOverview<
  TData = Awaited<ReturnType<typeof adminControllerOverview>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerOverview>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerOverview>>,
          TError,
          Awaited<ReturnType<typeof adminControllerOverview>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerOverview<
  TData = Awaited<ReturnType<typeof adminControllerOverview>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerOverview>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerOverview>>,
          TError,
          Awaited<ReturnType<typeof adminControllerOverview>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerOverview<
  TData = Awaited<ReturnType<typeof adminControllerOverview>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerOverview>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAdminControllerOverview<
  TData = Awaited<ReturnType<typeof adminControllerOverview>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerOverview>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminControllerOverviewQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getAdminControllerOverviewSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof adminControllerOverview>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof adminControllerOverview>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminControllerOverviewQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminControllerOverview>>
  > = ({ signal }) => adminControllerOverview(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof adminControllerOverview>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminControllerOverviewSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerOverview>>
>;
export type AdminControllerOverviewSuspenseQueryError = unknown;

export function useAdminControllerOverviewSuspense<
  TData = Awaited<ReturnType<typeof adminControllerOverview>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerOverview>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerOverviewSuspense<
  TData = Awaited<ReturnType<typeof adminControllerOverview>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerOverview>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerOverviewSuspense<
  TData = Awaited<ReturnType<typeof adminControllerOverview>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerOverview>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAdminControllerOverviewSuspense<
  TData = Awaited<ReturnType<typeof adminControllerOverview>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerOverview>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminControllerOverviewSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const adminControllerListUniversities = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/universities`,
    method: "GET",
    signal,
  });
};

export const getAdminControllerListUniversitiesQueryKey = () => {
  return [`/api/admin/universities`] as const;
};

export const getAdminControllerListUniversitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof adminControllerListUniversities>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof adminControllerListUniversities>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminControllerListUniversitiesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminControllerListUniversities>>
  > = ({ signal }) => adminControllerListUniversities(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminControllerListUniversities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminControllerListUniversitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerListUniversities>>
>;
export type AdminControllerListUniversitiesQueryError = unknown;

export function useAdminControllerListUniversities<
  TData = Awaited<ReturnType<typeof adminControllerListUniversities>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListUniversities>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerListUniversities>>,
          TError,
          Awaited<ReturnType<typeof adminControllerListUniversities>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListUniversities<
  TData = Awaited<ReturnType<typeof adminControllerListUniversities>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListUniversities>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerListUniversities>>,
          TError,
          Awaited<ReturnType<typeof adminControllerListUniversities>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListUniversities<
  TData = Awaited<ReturnType<typeof adminControllerListUniversities>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAdminControllerListUniversities<
  TData = Awaited<ReturnType<typeof adminControllerListUniversities>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminControllerListUniversitiesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getAdminControllerListUniversitiesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof adminControllerListUniversities>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof adminControllerListUniversities>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminControllerListUniversitiesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminControllerListUniversities>>
  > = ({ signal }) => adminControllerListUniversities(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof adminControllerListUniversities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminControllerListUniversitiesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerListUniversities>>
>;
export type AdminControllerListUniversitiesSuspenseQueryError = unknown;

export function useAdminControllerListUniversitiesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListUniversities>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListUniversitiesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListUniversities>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListUniversitiesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListUniversities>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAdminControllerListUniversitiesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListUniversities>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getAdminControllerListUniversitiesSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const adminControllerCreateUniversity = (
  createUniversityDto: CreateUniversityDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/universities`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createUniversityDto,
    signal,
  });
};

export const getAdminControllerCreateUniversityMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerCreateUniversity>>,
    TError,
    { data: CreateUniversityDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminControllerCreateUniversity>>,
  TError,
  { data: CreateUniversityDto },
  TContext
> => {
  const mutationKey = ["adminControllerCreateUniversity"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminControllerCreateUniversity>>,
    { data: CreateUniversityDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminControllerCreateUniversity(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminControllerCreateUniversityMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerCreateUniversity>>
>;
export type AdminControllerCreateUniversityMutationBody = CreateUniversityDto;
export type AdminControllerCreateUniversityMutationError = unknown;

export const useAdminControllerCreateUniversity = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminControllerCreateUniversity>>,
      TError,
      { data: CreateUniversityDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminControllerCreateUniversity>>,
  TError,
  { data: CreateUniversityDto },
  TContext
> => {
  const mutationOptions =
    getAdminControllerCreateUniversityMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminControllerDeactivateUniversity = (
  universityId: string | undefined | null,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/universities/${universityId}/deactivate`,
    method: "PATCH",
  });
};

export const getAdminControllerDeactivateUniversityMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerDeactivateUniversity>>,
    TError,
    { universityId: string | undefined | null },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminControllerDeactivateUniversity>>,
  TError,
  { universityId: string | undefined | null },
  TContext
> => {
  const mutationKey = ["adminControllerDeactivateUniversity"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminControllerDeactivateUniversity>>,
    { universityId: string | undefined | null }
  > = (props) => {
    const { universityId } = props ?? {};

    return adminControllerDeactivateUniversity(universityId);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminControllerDeactivateUniversityMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerDeactivateUniversity>>
>;

export type AdminControllerDeactivateUniversityMutationError = unknown;

export const useAdminControllerDeactivateUniversity = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminControllerDeactivateUniversity>>,
      TError,
      { universityId: string | undefined | null },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminControllerDeactivateUniversity>>,
  TError,
  { universityId: string | undefined | null },
  TContext
> => {
  const mutationOptions =
    getAdminControllerDeactivateUniversityMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminControllerReactivateUniversity = (
  universityId: string | undefined | null,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/universities/${universityId}/reactivate`,
    method: "PATCH",
  });
};

export const getAdminControllerReactivateUniversityMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerReactivateUniversity>>,
    TError,
    { universityId: string | undefined | null },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminControllerReactivateUniversity>>,
  TError,
  { universityId: string | undefined | null },
  TContext
> => {
  const mutationKey = ["adminControllerReactivateUniversity"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminControllerReactivateUniversity>>,
    { universityId: string | undefined | null }
  > = (props) => {
    const { universityId } = props ?? {};

    return adminControllerReactivateUniversity(universityId);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminControllerReactivateUniversityMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerReactivateUniversity>>
>;

export type AdminControllerReactivateUniversityMutationError = unknown;

export const useAdminControllerReactivateUniversity = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminControllerReactivateUniversity>>,
      TError,
      { universityId: string | undefined | null },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminControllerReactivateUniversity>>,
  TError,
  { universityId: string | undefined | null },
  TContext
> => {
  const mutationOptions =
    getAdminControllerReactivateUniversityMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminControllerSeedOrReassignSuperadmin = (
  universityId: string | undefined | null,
  seedSuperadminDto: SeedSuperadminDto,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/universities/${universityId}/superadmin`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: seedSuperadminDto,
  });
};

export const getAdminControllerSeedOrReassignSuperadminMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerSeedOrReassignSuperadmin>>,
    TError,
    { universityId: string | undefined | null; data: SeedSuperadminDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminControllerSeedOrReassignSuperadmin>>,
  TError,
  { universityId: string | undefined | null; data: SeedSuperadminDto },
  TContext
> => {
  const mutationKey = ["adminControllerSeedOrReassignSuperadmin"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminControllerSeedOrReassignSuperadmin>>,
    { universityId: string | undefined | null; data: SeedSuperadminDto }
  > = (props) => {
    const { universityId, data } = props ?? {};

    return adminControllerSeedOrReassignSuperadmin(universityId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminControllerSeedOrReassignSuperadminMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerSeedOrReassignSuperadmin>>
>;
export type AdminControllerSeedOrReassignSuperadminMutationBody =
  SeedSuperadminDto;
export type AdminControllerSeedOrReassignSuperadminMutationError = unknown;

export const useAdminControllerSeedOrReassignSuperadmin = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminControllerSeedOrReassignSuperadmin>>,
      TError,
      { universityId: string | undefined | null; data: SeedSuperadminDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminControllerSeedOrReassignSuperadmin>>,
  TError,
  { universityId: string | undefined | null; data: SeedSuperadminDto },
  TContext
> => {
  const mutationOptions =
    getAdminControllerSeedOrReassignSuperadminMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminControllerListCompanies = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/companies`,
    method: "GET",
    signal,
  });
};

export const getAdminControllerListCompaniesQueryKey = () => {
  return [`/api/admin/companies`] as const;
};

export const getAdminControllerListCompaniesQueryOptions = <
  TData = Awaited<ReturnType<typeof adminControllerListCompanies>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof adminControllerListCompanies>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminControllerListCompaniesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminControllerListCompanies>>
  > = ({ signal }) => adminControllerListCompanies(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminControllerListCompanies>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminControllerListCompaniesQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerListCompanies>>
>;
export type AdminControllerListCompaniesQueryError = unknown;

export function useAdminControllerListCompanies<
  TData = Awaited<ReturnType<typeof adminControllerListCompanies>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListCompanies>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerListCompanies>>,
          TError,
          Awaited<ReturnType<typeof adminControllerListCompanies>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListCompanies<
  TData = Awaited<ReturnType<typeof adminControllerListCompanies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListCompanies>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerListCompanies>>,
          TError,
          Awaited<ReturnType<typeof adminControllerListCompanies>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListCompanies<
  TData = Awaited<ReturnType<typeof adminControllerListCompanies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListCompanies>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAdminControllerListCompanies<
  TData = Awaited<ReturnType<typeof adminControllerListCompanies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListCompanies>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminControllerListCompaniesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getAdminControllerListCompaniesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof adminControllerListCompanies>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof adminControllerListCompanies>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminControllerListCompaniesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminControllerListCompanies>>
  > = ({ signal }) => adminControllerListCompanies(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof adminControllerListCompanies>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminControllerListCompaniesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerListCompanies>>
>;
export type AdminControllerListCompaniesSuspenseQueryError = unknown;

export function useAdminControllerListCompaniesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListCompanies>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListCompanies>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListCompaniesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListCompanies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListCompanies>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListCompaniesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListCompanies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListCompanies>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAdminControllerListCompaniesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListCompanies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListCompanies>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getAdminControllerListCompaniesSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const adminControllerDeactivateCompany = (
  companyId: string | undefined | null,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/companies/${companyId}/deactivate`,
    method: "PATCH",
  });
};

export const getAdminControllerDeactivateCompanyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerDeactivateCompany>>,
    TError,
    { companyId: string | undefined | null },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminControllerDeactivateCompany>>,
  TError,
  { companyId: string | undefined | null },
  TContext
> => {
  const mutationKey = ["adminControllerDeactivateCompany"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminControllerDeactivateCompany>>,
    { companyId: string | undefined | null }
  > = (props) => {
    const { companyId } = props ?? {};

    return adminControllerDeactivateCompany(companyId);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminControllerDeactivateCompanyMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerDeactivateCompany>>
>;

export type AdminControllerDeactivateCompanyMutationError = unknown;

export const useAdminControllerDeactivateCompany = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminControllerDeactivateCompany>>,
      TError,
      { companyId: string | undefined | null },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminControllerDeactivateCompany>>,
  TError,
  { companyId: string | undefined | null },
  TContext
> => {
  const mutationOptions =
    getAdminControllerDeactivateCompanyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminControllerPatchCompanyAdmin = (
  companyId: string | undefined | null,
  patchCompanyAdminDto: PatchCompanyAdminDto,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/companies/${companyId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchCompanyAdminDto,
  });
};

export const getAdminControllerPatchCompanyAdminMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerPatchCompanyAdmin>>,
    TError,
    { companyId: string | undefined | null; data: PatchCompanyAdminDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminControllerPatchCompanyAdmin>>,
  TError,
  { companyId: string | undefined | null; data: PatchCompanyAdminDto },
  TContext
> => {
  const mutationKey = ["adminControllerPatchCompanyAdmin"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminControllerPatchCompanyAdmin>>,
    { companyId: string | undefined | null; data: PatchCompanyAdminDto }
  > = (props) => {
    const { companyId, data } = props ?? {};

    return adminControllerPatchCompanyAdmin(companyId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminControllerPatchCompanyAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerPatchCompanyAdmin>>
>;
export type AdminControllerPatchCompanyAdminMutationBody = PatchCompanyAdminDto;
export type AdminControllerPatchCompanyAdminMutationError = unknown;

export const useAdminControllerPatchCompanyAdmin = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminControllerPatchCompanyAdmin>>,
      TError,
      { companyId: string | undefined | null; data: PatchCompanyAdminDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminControllerPatchCompanyAdmin>>,
  TError,
  { companyId: string | undefined | null; data: PatchCompanyAdminDto },
  TContext
> => {
  const mutationOptions =
    getAdminControllerPatchCompanyAdminMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminControllerListTemplates = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/templates`,
    method: "GET",
    signal,
  });
};

export const getAdminControllerListTemplatesQueryKey = () => {
  return [`/api/admin/templates`] as const;
};

export const getAdminControllerListTemplatesQueryOptions = <
  TData = Awaited<ReturnType<typeof adminControllerListTemplates>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof adminControllerListTemplates>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminControllerListTemplatesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminControllerListTemplates>>
  > = ({ signal }) => adminControllerListTemplates(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminControllerListTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminControllerListTemplatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerListTemplates>>
>;
export type AdminControllerListTemplatesQueryError = unknown;

export function useAdminControllerListTemplates<
  TData = Awaited<ReturnType<typeof adminControllerListTemplates>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerListTemplates>>,
          TError,
          Awaited<ReturnType<typeof adminControllerListTemplates>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListTemplates<
  TData = Awaited<ReturnType<typeof adminControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerListTemplates>>,
          TError,
          Awaited<ReturnType<typeof adminControllerListTemplates>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListTemplates<
  TData = Awaited<ReturnType<typeof adminControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAdminControllerListTemplates<
  TData = Awaited<ReturnType<typeof adminControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminControllerListTemplatesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getAdminControllerListTemplatesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof adminControllerListTemplates>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof adminControllerListTemplates>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminControllerListTemplatesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminControllerListTemplates>>
  > = ({ signal }) => adminControllerListTemplates(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof adminControllerListTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminControllerListTemplatesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerListTemplates>>
>;
export type AdminControllerListTemplatesSuspenseQueryError = unknown;

export function useAdminControllerListTemplatesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListTemplates>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListTemplatesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerListTemplatesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAdminControllerListTemplatesSuspense<
  TData = Awaited<ReturnType<typeof adminControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getAdminControllerListTemplatesSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const adminControllerCreateTemplate = (
  createTemplateDto: CreateTemplateDto,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`name`, createTemplateDto.name);
  if (createTemplateDto.description !== undefined) {
    formData.append(`description`, createTemplateDto.description);
  }
  if (createTemplateDto.field_schema !== undefined) {
    formData.append(`field_schema`, createTemplateDto.field_schema);
  }
  formData.append(`term_months`, createTemplateDto.term_months.toString());
  formData.append(`page_count`, createTemplateDto.page_count.toString());
  formData.append(`page_w`, createTemplateDto.page_w.toString());
  formData.append(`page_h`, createTemplateDto.page_h.toString());

  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/templates`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    signal,
  });
};

export const getAdminControllerCreateTemplateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerCreateTemplate>>,
    TError,
    { data: CreateTemplateDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminControllerCreateTemplate>>,
  TError,
  { data: CreateTemplateDto },
  TContext
> => {
  const mutationKey = ["adminControllerCreateTemplate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminControllerCreateTemplate>>,
    { data: CreateTemplateDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminControllerCreateTemplate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminControllerCreateTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerCreateTemplate>>
>;
export type AdminControllerCreateTemplateMutationBody = CreateTemplateDto;
export type AdminControllerCreateTemplateMutationError = unknown;

export const useAdminControllerCreateTemplate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminControllerCreateTemplate>>,
      TError,
      { data: CreateTemplateDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminControllerCreateTemplate>>,
  TError,
  { data: CreateTemplateDto },
  TContext
> => {
  const mutationOptions =
    getAdminControllerCreateTemplateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminControllerPatchTemplate = (
  templateId: string | undefined | null,
  patchTemplateDto: PatchTemplateDto,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/templates/${templateId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchTemplateDto,
  });
};

export const getAdminControllerPatchTemplateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerPatchTemplate>>,
    TError,
    { templateId: string | undefined | null; data: PatchTemplateDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminControllerPatchTemplate>>,
  TError,
  { templateId: string | undefined | null; data: PatchTemplateDto },
  TContext
> => {
  const mutationKey = ["adminControllerPatchTemplate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminControllerPatchTemplate>>,
    { templateId: string | undefined | null; data: PatchTemplateDto }
  > = (props) => {
    const { templateId, data } = props ?? {};

    return adminControllerPatchTemplate(templateId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminControllerPatchTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerPatchTemplate>>
>;
export type AdminControllerPatchTemplateMutationBody = PatchTemplateDto;
export type AdminControllerPatchTemplateMutationError = unknown;

export const useAdminControllerPatchTemplate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminControllerPatchTemplate>>,
      TError,
      { templateId: string | undefined | null; data: PatchTemplateDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminControllerPatchTemplate>>,
  TError,
  { templateId: string | undefined | null; data: PatchTemplateDto },
  TContext
> => {
  const mutationOptions =
    getAdminControllerPatchTemplateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminControllerDeleteTemplate = (
  templateId: string | undefined | null,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/admin/templates/${templateId}`,
    method: "DELETE",
  });
};

export const getAdminControllerDeleteTemplateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerDeleteTemplate>>,
    TError,
    { templateId: string | undefined | null },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminControllerDeleteTemplate>>,
  TError,
  { templateId: string | undefined | null },
  TContext
> => {
  const mutationKey = ["adminControllerDeleteTemplate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminControllerDeleteTemplate>>,
    { templateId: string | undefined | null }
  > = (props) => {
    const { templateId } = props ?? {};

    return adminControllerDeleteTemplate(templateId);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminControllerDeleteTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerDeleteTemplate>>
>;

export type AdminControllerDeleteTemplateMutationError = unknown;

export const useAdminControllerDeleteTemplate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminControllerDeleteTemplate>>,
      TError,
      { templateId: string | undefined | null },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminControllerDeleteTemplate>>,
  TError,
  { templateId: string | undefined | null },
  TContext
> => {
  const mutationOptions =
    getAdminControllerDeleteTemplateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
