/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type AdminCompanyListItemDtoVerificationReason =
  | (typeof AdminCompanyListItemDtoVerificationReason)[keyof typeof AdminCompanyListItemDtoVerificationReason]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminCompanyListItemDtoVerificationReason = {
  rejected: "rejected",
  expired: "expired",
} as const;
