/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminCompanyListItemDtoVerificationStatus } from "./adminCompanyListItemDtoVerificationStatus";
import type { AdminCompanyListItemDtoVerificationReason } from "./adminCompanyListItemDtoVerificationReason";

export interface AdminCompanyListItemDto {
  id: string;
  /** @nullable */
  registered_name: string | null;
  /** @nullable */
  registered_address: string | null;
  /** @nullable */
  company_type: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  email_verified: boolean | null;
  /** @nullable */
  is_deactivated: boolean | null;
  created_at: string;
  has_pending_review: boolean;
  is_profile_incomplete: boolean;
  verification_status: AdminCompanyListItemDtoVerificationStatus;
  /** @nullable */
  verification_reason: AdminCompanyListItemDtoVerificationReason;
}
