/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminCompanyDetailVerificationDtoStatus } from "./adminCompanyDetailVerificationDtoStatus";
import type { AdminCompanyDetailVerificationDtoReason } from "./adminCompanyDetailVerificationDtoReason";
import type { AdminCompanyDetailVerificationDtoDocumentRejections } from "./adminCompanyDetailVerificationDtoDocumentRejections";

export interface AdminCompanyDetailVerificationDto {
  status: AdminCompanyDetailVerificationDtoStatus;
  /** @nullable */
  reason: AdminCompanyDetailVerificationDtoReason;
  documentRejections: AdminCompanyDetailVerificationDtoDocumentRejections;
  /** @nullable */
  expiredDocument: string | null;
  /** @nullable */
  approvalExpiresAt: string | null;
}
