/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export interface AdminSettingsResponse {
  success: boolean;
  message?: string;
  /** @nullable */
  default_template_id: string | null;
  /** @nullable */
  witness_name: string | null;
  /** @nullable */
  witness_title: string | null;
  /** @nullable */
  witness_signature_url: string | null;
}
