/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { ApproveCompanyReviewDtoCompanyType } from "./approveCompanyReviewDtoCompanyType";
import type { ApproveCompanyReviewDtoDocumentExpiries } from "./approveCompanyReviewDtoDocumentExpiries";

export interface ApproveCompanyReviewDto {
  registered_name: string;
  tin: string;
  company_type: ApproveCompanyReviewDtoCompanyType;
  registered_address: string;
  date_of_incorporation: string;
  company_registry_number: string;
  document_expiries: ApproveCompanyReviewDtoDocumentExpiries;
}
