/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyVerificationResponseStatus } from "./companyVerificationResponseStatus";
import type { CompanyVerificationResponseReason } from "./companyVerificationResponseReason";
import type { CompanyVerificationResponseDocumentRejections } from "./companyVerificationResponseDocumentRejections";

export interface CompanyVerificationResponse {
  success: boolean;
  message?: string;
  status: CompanyVerificationResponseStatus;
  /** @nullable */
  reason: CompanyVerificationResponseReason;
  documentRejections: CompanyVerificationResponseDocumentRejections;
  /** @nullable */
  expiredDocument: string | null;
  canPostListing: boolean;
  /** @nullable */
  approvalExpiresAt: string | null;
}
