/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyIdentityClaimDtoClaimedCompanyType } from "./companyIdentityClaimDtoClaimedCompanyType";

export interface CompanyIdentityClaimDto {
  /** @nullable */
  claimed_company_type: CompanyIdentityClaimDtoClaimedCompanyType;
  claimed_registered_name?: string;
  claimed_registered_address?: string;
}
