/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export type CompanyCreateMoaRequestResponseKind =
  (typeof CompanyCreateMoaRequestResponseKind)[keyof typeof CompanyCreateMoaRequestResponseKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompanyCreateMoaRequestResponseKind = {
  issuing: "issuing",
  parked: "parked",
} as const;
