/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyMoaRequestDtoStatus } from "./companyMoaRequestDtoStatus";
import type { CompanyMoaRequestDtoUniversity } from "./companyMoaRequestDtoUniversity";
import type { CompanyMoaRequestDtoTemplate } from "./companyMoaRequestDtoTemplate";

export interface CompanyMoaRequestDto {
  id: string;
  status: CompanyMoaRequestDtoStatus;
  /** @nullable */
  signatory_email: string | null;
  /** @nullable */
  signatory_name: string | null;
  /** @nullable */
  signatory_title: string | null;
  auto_signed: boolean;
  /** @nullable */
  failure_reason: string | null;
  /** @nullable */
  moa_id: string | null;
  created_at: string;
  /** @nullable */
  university: CompanyMoaRequestDtoUniversity;
  /** @nullable */
  template: CompanyMoaRequestDtoTemplate;
}
