/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyMoaRequestDto } from "./companyMoaRequestDto";
import type { CompanyCreateMoaRequestResponseKind } from "./companyCreateMoaRequestResponseKind";

export interface CompanyCreateMoaRequestResponse {
  success: boolean;
  message?: string;
  request: CompanyMoaRequestDto;
  kind: CompanyCreateMoaRequestResponseKind;
}
