/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyOtpVerifyResponseKind } from "./companyOtpVerifyResponseKind";
import type { CareerLinkResponse } from "./careerLinkResponse";

export interface CompanyOtpVerifyResponse {
  success: boolean;
  message?: string;
  kind: CompanyOtpVerifyResponseKind;
  university_id?: string;
  /** @nullable */
  template_id?: string | null;
  /** @nullable */
  magicLink?: string | null;
  conflictEmail?: string;
  autoLinkToken?: string;
  careerLink?: CareerLinkResponse;
}
