/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export type CompanyMoaRequestDtoStatus =
  (typeof CompanyMoaRequestDtoStatus)[keyof typeof CompanyMoaRequestDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompanyMoaRequestDtoStatus = {
  awaiting_signature: "awaiting_signature",
  awaiting_verification: "awaiting_verification",
  issued: "issued",
  cancelled: "cancelled",
  expired: "expired",
  failed: "failed",
} as const;
