/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyAutoRequestOfferDtoSignatureType } from "./companyAutoRequestOfferDtoSignatureType";

export interface CompanyAutoRequestOfferDto {
  templateId: string;
  templateName: string;
  isPerpetual: boolean;
  proactive: boolean;
  autoRenew: boolean;
  signatoryName: string;
  signatoryTitle: string;
  signatureType: CompanyAutoRequestOfferDtoSignatureType;
  signatureData: string;
  signedAt: string;
}
