/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyControllerCreateMoaRequestBodyMode } from "./companyControllerCreateMoaRequestBodyMode";

export type CompanyControllerCreateMoaRequestBody = {
  universityId: string;
  templateId: string;
  mode: CompanyControllerCreateMoaRequestBodyMode;
  inviteId?: string;
  signatoryName?: string;
  signatoryTitle?: string;
  signatureText?: string;
  signatoryEmail?: string;
  signature?: Blob;
};
