/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyConsentDtoKind } from "./companyConsentDtoKind";

export interface CompanyConsentDto {
  id: string;
  templateId: string;
  templateName: string;
  kind: CompanyConsentDtoKind;
  email: string;
  proactive: boolean;
  autoRenew: boolean;
  signatoryName: string;
  signatoryTitle: string;
  createdAt: string;
}
