/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export type CompanyConsentDtoKind =
  (typeof CompanyConsentDtoKind)[keyof typeof CompanyConsentDtoKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompanyConsentDtoKind = {
  delegate: "delegate",
  owner: "owner",
} as const;
