/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export interface CreateTemplateDto {
  name: string;
  description?: string;
  /** JSON string of field_schema array */
  field_schema?: string;
  term_months: number;
  page_count: number;
  page_w: number;
  page_h: number;
}
