/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export * from "./adminLoginDto";
export * from "./adminOverviewResponse";
export * from "./approveCompanyReviewDto";
export * from "./approveCompanyReviewDtoDocumentReviewDetails";
export * from "./baseResponse";
export * from "./blacklistCompanyDto";
export * from "./claimInviteDto";
export * from "./companyAuthListItemDto";
export * from "./companyAuthListResponse";
export * from "./companyDto";
export * from "./companyDtoCosmetic";
export * from "./companyForgotDto";
export * from "./companyForgotResponse";
export * from "./companyLoginDto";
export * from "./companyLoginInviteResponse";
export * from "./companyMeResponse";
export * from "./companyOtpRequestDto";
export * from "./companyOtpRequestResponse";
export * from "./companyOtpVerifyDto";
export * from "./companyPatchProfileResponse";
export * from "./companyPendingInviteDto";
export * from "./companyPendingInviteDtoTemplate";
export * from "./companyPendingInviteDtoUniversity";
export * from "./companyPendingInviteTemplateDto";
export * from "./companyPendingInviteUniversityDto";
export * from "./companyPendingInvitesResponse";
export * from "./companyRegisterDto";
export * from "./companyRegisterInvitedResponse";
export * from "./companyRegisterResponse";
export * from "./companyResetDto";
export * from "./companyVerificationResponse";
export * from "./createCompanyAdminDto";
export * from "./createCompanyAdminDtoCompanyType";
export * from "./createCompanyInviteDto";
export * from "./createLegacyMoaDto";
export * from "./createStaffAccountDto";
export * from "./createTemplateDto";
export * from "./createUniversityDto";
export * from "./errorResponse";
export * from "./inviteControllerResolveCompanyInviteParams";
export * from "./patchCompanyAdminDto";
export * from "./patchCompanyProfileDto";
export * from "./patchCompanyProfileDtoCompanyType";
export * from "./patchTemplateDto";
export * from "./patchUniversityProfileDto";
export * from "./registerInvitedCompanyDto";
export * from "./rejectCompanyReviewDto";
export * from "./requestMoaDto";
export * from "./resolveFileDto";
export * from "./resolveFileDtoKind";
export * from "./seedSuperadminDto";
export * from "./toggleTemplateOfferDto";
export * from "./universityAcceptInviteDto";
export * from "./universityAccountDto";
export * from "./universityDto";
export * from "./universityForgotDto";
export * from "./universityGetProfileResponse";
export * from "./universityLoginDto";
export * from "./universityMeResponse";
export * from "./universityPatchProfileResponse";
export * from "./universityResetDto";
export * from "./updateStaffAccountDto";
export * from "./verifyTinDto";
