/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export * from "./adminLoginDto";
export * from "./blacklistCompanyDto";
export * from "./companyForgotDto";
export * from "./companyLoginDto";
export * from "./companyOtpRequestDto";
export * from "./companyOtpVerifyDto";
export * from "./companyRegisterDto";
export * from "./companyResetDto";
export * from "./createStaffAccountDto";
export * from "./createTemplateDto";
export * from "./createUniversityDto";
export * from "./patchCompanyAdminDto";
export * from "./patchCompanyProfileDto";
export * from "./patchCompanyProfileDtoCompanyType";
export * from "./patchTemplateDto";
export * from "./patchUniversityProfileDto";
export * from "./rejectMoaDto";
export * from "./requestMoaDto";
export * from "./resolveFileDto";
export * from "./resolveFileDtoKind";
export * from "./seedSuperadminDto";
export * from "./toggleTemplateOfferDto";
export * from "./universityAcceptInviteDto";
export * from "./universityForgotDto";
export * from "./universityLoginDto";
export * from "./universityResetDto";
export * from "./updateStaffAccountDto";
