/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export type PatchCompanyProfileDtoCompanyType =
  (typeof PatchCompanyProfileDtoCompanyType)[keyof typeof PatchCompanyProfileDtoCompanyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchCompanyProfileDtoCompanyType = {
  corporation: "corporation",
  partnership: "partnership",
  sole_proprietorship: "sole_proprietorship",
  government_agency: "government_agency",
} as const;
