/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { RevokeTokenResolvedResponseKind } from "./revokeTokenResolvedResponseKind";

export interface RevokeTokenResolvedResponse {
  success: boolean;
  message?: string;
  kind: RevokeTokenResolvedResponseKind;
  templateName: string;
  proactive?: boolean;
  autoRenew?: boolean;
  isPerpetual?: boolean;
  active?: boolean;
}
