/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { SubmitSignatureResponseKind } from "./submitSignatureResponseKind";

export interface SubmitSignatureResponse {
  success: boolean;
  message?: string;
  kind: SubmitSignatureResponseKind;
  /** @nullable */
  verificationCode: string | null;
}
