/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export type UniversityControllerBulkCreateLegacyCompaniesFromWizardBody = {
  /** JSON array of MOA records: [{ company_name, effective_date, expiry_date, is_perpetual, document_file_index }] */
  moas: string;
  moaDocuments: Blob[];
};
