/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityToggleOfferDto } from "./universityToggleOfferDto";

export interface UniversityToggleOfferResponse {
  success: boolean;
  message?: string;
  offer: UniversityToggleOfferDto;
  /** Whether this flip queued a fan-out — the actual count arrives asynchronously. */
  will_fan_out: boolean;
}
