/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityListingInviteListItemDtoRegisteredCompany } from "./universityListingInviteListItemDtoRegisteredCompany";

export interface UniversityListingInviteListItemDto {
  id: string;
  invited_email: string;
  /** @nullable */
  company_name: string | null;
  /** @nullable */
  personal_message: string | null;
  status: string;
  created_at: string;
  expires_at: string;
  /** @nullable */
  registered_company: UniversityListingInviteListItemDtoRegisteredCompany;
}
