/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export interface UpdateLegacyMoaDto {
  /** @nullable */
  effective_date: string | null;
  /** @nullable */
  expiry_date: string | null;
  is_perpetual: boolean;
  /** @nullable */
  filename: string | null;
  /** @nullable */
  notes: string | null;
}
