/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  BaseResponse,
  ErrorResponse,
  UniversityOtpRequestDto,
  UniversityOtpRequestResponse,
  UniversityOtpVerifyDto,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const universityAuthControllerOtpRequest = (
  universityOtpRequestDto: UniversityOtpRequestDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<UniversityOtpRequestResponse>({
    url: `/api/auth/university/otp/request`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: universityOtpRequestDto,
    signal,
  });
};

export const getUniversityAuthControllerOtpRequestMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityAuthControllerOtpRequest>>,
    TError,
    { data: UniversityOtpRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityAuthControllerOtpRequest>>,
  TError,
  { data: UniversityOtpRequestDto },
  TContext
> => {
  const mutationKey = ["universityAuthControllerOtpRequest"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityAuthControllerOtpRequest>>,
    { data: UniversityOtpRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return universityAuthControllerOtpRequest(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityAuthControllerOtpRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityAuthControllerOtpRequest>>
>;
export type UniversityAuthControllerOtpRequestMutationBody =
  UniversityOtpRequestDto;
export type UniversityAuthControllerOtpRequestMutationError = ErrorResponse;

export const useUniversityAuthControllerOtpRequest = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityAuthControllerOtpRequest>>,
      TError,
      { data: UniversityOtpRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityAuthControllerOtpRequest>>,
  TError,
  { data: UniversityOtpRequestDto },
  TContext
> => {
  const mutationOptions =
    getUniversityAuthControllerOtpRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityAuthControllerOtpVerify = (
  universityOtpVerifyDto: UniversityOtpVerifyDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/university/otp/verify`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: universityOtpVerifyDto,
    signal,
  });
};

export const getUniversityAuthControllerOtpVerifyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityAuthControllerOtpVerify>>,
    TError,
    { data: UniversityOtpVerifyDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityAuthControllerOtpVerify>>,
  TError,
  { data: UniversityOtpVerifyDto },
  TContext
> => {
  const mutationKey = ["universityAuthControllerOtpVerify"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityAuthControllerOtpVerify>>,
    { data: UniversityOtpVerifyDto }
  > = (props) => {
    const { data } = props ?? {};

    return universityAuthControllerOtpVerify(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityAuthControllerOtpVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityAuthControllerOtpVerify>>
>;
export type UniversityAuthControllerOtpVerifyMutationBody =
  UniversityOtpVerifyDto;
export type UniversityAuthControllerOtpVerifyMutationError = ErrorResponse;

export const useUniversityAuthControllerOtpVerify = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityAuthControllerOtpVerify>>,
      TError,
      { data: UniversityOtpVerifyDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityAuthControllerOtpVerify>>,
  TError,
  { data: UniversityOtpVerifyDto },
  TContext
> => {
  const mutationOptions =
    getUniversityAuthControllerOtpVerifyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityAuthControllerLogout = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/university/logout`,
    method: "POST",
    signal,
  });
};

export const getUniversityAuthControllerLogoutMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityAuthControllerLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["universityAuthControllerLogout"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityAuthControllerLogout>>,
    void
  > = () => {
    return universityAuthControllerLogout();
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityAuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityAuthControllerLogout>>
>;

export type UniversityAuthControllerLogoutMutationError = ErrorResponse;

export const useUniversityAuthControllerLogout = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityAuthControllerLogout>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getUniversityAuthControllerLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
