/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  BlacklistCompanyDto,
  CreateStaffAccountDto,
  PatchUniversityProfileDto,
  ToggleTemplateOfferDto,
  UpdateStaffAccountDto,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const universityControllerMe = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/me`,
    method: "GET",
    signal,
  });
};

export const getUniversityControllerMeQueryKey = () => {
  return [`/api/university/me`] as const;
};

export const getUniversityControllerMeQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerMe>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof universityControllerMe>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerMeQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerMe>>
  > = ({ signal }) => universityControllerMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof universityControllerMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerMe>>
>;
export type UniversityControllerMeQueryError = unknown;

export function useUniversityControllerMe<
  TData = Awaited<ReturnType<typeof universityControllerMe>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerMe>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerMe>>,
          TError,
          Awaited<ReturnType<typeof universityControllerMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerMe<
  TData = Awaited<ReturnType<typeof universityControllerMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerMe>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerMe>>,
          TError,
          Awaited<ReturnType<typeof universityControllerMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerMe<
  TData = Awaited<ReturnType<typeof universityControllerMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerMe<
  TData = Awaited<ReturnType<typeof universityControllerMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUniversityControllerMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUniversityControllerMeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerMe>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof universityControllerMe>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerMeQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerMe>>
  > = ({ signal }) => universityControllerMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof universityControllerMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerMeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerMe>>
>;
export type UniversityControllerMeSuspenseQueryError = unknown;

export function useUniversityControllerMeSuspense<
  TData = Awaited<ReturnType<typeof universityControllerMe>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerMeSuspense<
  TData = Awaited<ReturnType<typeof universityControllerMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerMeSuspense<
  TData = Awaited<ReturnType<typeof universityControllerMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerMeSuspense<
  TData = Awaited<ReturnType<typeof universityControllerMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUniversityControllerMeSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const universityControllerGetProfile = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/profile`,
    method: "GET",
    signal,
  });
};

export const getUniversityControllerGetProfileQueryKey = () => {
  return [`/api/university/profile`] as const;
};

export const getUniversityControllerGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetProfile>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof universityControllerGetProfile>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerGetProfileQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetProfile>>
  > = ({ signal }) => universityControllerGetProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetProfile>>
>;
export type UniversityControllerGetProfileQueryError = unknown;

export function useUniversityControllerGetProfile<
  TData = Awaited<ReturnType<typeof universityControllerGetProfile>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetProfile>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetProfile>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetProfile<
  TData = Awaited<ReturnType<typeof universityControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetProfile>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetProfile>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetProfile<
  TData = Awaited<ReturnType<typeof universityControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetProfile>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetProfile<
  TData = Awaited<ReturnType<typeof universityControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetProfile>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUniversityControllerGetProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUniversityControllerGetProfileSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetProfile>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof universityControllerGetProfile>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerGetProfileQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetProfile>>
  > = ({ signal }) => universityControllerGetProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetProfileSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetProfile>>
>;
export type UniversityControllerGetProfileSuspenseQueryError = unknown;

export function useUniversityControllerGetProfileSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetProfile>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetProfile>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetProfileSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetProfile>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetProfileSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetProfile>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetProfileSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetProfile>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getUniversityControllerGetProfileSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const universityControllerPatchProfile = (
  patchUniversityProfileDto: PatchUniversityProfileDto,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/profile`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchUniversityProfileDto,
  });
};

export const getUniversityControllerPatchProfileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityControllerPatchProfile>>,
    TError,
    { data: PatchUniversityProfileDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityControllerPatchProfile>>,
  TError,
  { data: PatchUniversityProfileDto },
  TContext
> => {
  const mutationKey = ["universityControllerPatchProfile"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityControllerPatchProfile>>,
    { data: PatchUniversityProfileDto }
  > = (props) => {
    const { data } = props ?? {};

    return universityControllerPatchProfile(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityControllerPatchProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerPatchProfile>>
>;
export type UniversityControllerPatchProfileMutationBody =
  PatchUniversityProfileDto;
export type UniversityControllerPatchProfileMutationError = unknown;

export const useUniversityControllerPatchProfile = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityControllerPatchProfile>>,
      TError,
      { data: PatchUniversityProfileDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityControllerPatchProfile>>,
  TError,
  { data: PatchUniversityProfileDto },
  TContext
> => {
  const mutationOptions =
    getUniversityControllerPatchProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityControllerUploadLogo = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/profile/logo`,
    method: "POST",
    signal,
  });
};

export const getUniversityControllerUploadLogoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityControllerUploadLogo>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityControllerUploadLogo>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["universityControllerUploadLogo"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityControllerUploadLogo>>,
    void
  > = () => {
    return universityControllerUploadLogo();
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityControllerUploadLogoMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerUploadLogo>>
>;

export type UniversityControllerUploadLogoMutationError = unknown;

export const useUniversityControllerUploadLogo = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityControllerUploadLogo>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityControllerUploadLogo>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getUniversityControllerUploadLogoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityControllerUploadSignature = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/profile/signature`,
    method: "POST",
    signal,
  });
};

export const getUniversityControllerUploadSignatureMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityControllerUploadSignature>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityControllerUploadSignature>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["universityControllerUploadSignature"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityControllerUploadSignature>>,
    void
  > = () => {
    return universityControllerUploadSignature();
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityControllerUploadSignatureMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerUploadSignature>>
>;

export type UniversityControllerUploadSignatureMutationError = unknown;

export const useUniversityControllerUploadSignature = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityControllerUploadSignature>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityControllerUploadSignature>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getUniversityControllerUploadSignatureMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityControllerGetMoaDetail = (
  moaId: string | undefined | null,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/moas/${moaId}`,
    method: "GET",
    signal,
  });
};

export const getUniversityControllerGetMoaDetailQueryKey = (
  moaId?: string | undefined | null,
) => {
  return [`/api/university/moas/${moaId}`] as const;
};

export const getUniversityControllerGetMoaDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
  TError = unknown,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getUniversityControllerGetMoaDetailQueryKey(moaId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetMoaDetail>>
  > = ({ signal }) => universityControllerGetMoaDetail(moaId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!moaId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetMoaDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetMoaDetail>>
>;
export type UniversityControllerGetMoaDetailQueryError = unknown;

export function useUniversityControllerGetMoaDetail<
  TData = Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
  TError = unknown,
>(
  moaId: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetMoaDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetMoaDetail<
  TData = Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
  TError = unknown,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetMoaDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetMoaDetail<
  TData = Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
  TError = unknown,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetMoaDetail<
  TData = Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
  TError = unknown,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUniversityControllerGetMoaDetailQueryOptions(
    moaId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUniversityControllerGetMoaDetailSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
  TError = unknown,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getUniversityControllerGetMoaDetailQueryKey(moaId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetMoaDetail>>
  > = ({ signal }) => universityControllerGetMoaDetail(moaId, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetMoaDetailSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetMoaDetail>>
>;
export type UniversityControllerGetMoaDetailSuspenseQueryError = unknown;

export function useUniversityControllerGetMoaDetailSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
  TError = unknown,
>(
  moaId: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetMoaDetailSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
  TError = unknown,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetMoaDetailSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
  TError = unknown,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetMoaDetailSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
  TError = unknown,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetMoaDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUniversityControllerGetMoaDetailSuspenseQueryOptions(
    moaId,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const universityControllerGetPartnerMoas = (
  companyId: string | undefined | null,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/partners/${companyId}/moas`,
    method: "GET",
    signal,
  });
};

export const getUniversityControllerGetPartnerMoasQueryKey = (
  companyId?: string | undefined | null,
) => {
  return [`/api/university/partners/${companyId}/moas`] as const;
};

export const getUniversityControllerGetPartnerMoasQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
  TError = unknown,
>(
  companyId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getUniversityControllerGetPartnerMoasQueryKey(companyId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>
  > = ({ signal }) => universityControllerGetPartnerMoas(companyId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!companyId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetPartnerMoasQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>
>;
export type UniversityControllerGetPartnerMoasQueryError = unknown;

export function useUniversityControllerGetPartnerMoas<
  TData = Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
  TError = unknown,
>(
  companyId: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetPartnerMoas<
  TData = Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
  TError = unknown,
>(
  companyId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetPartnerMoas<
  TData = Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
  TError = unknown,
>(
  companyId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetPartnerMoas<
  TData = Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
  TError = unknown,
>(
  companyId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUniversityControllerGetPartnerMoasQueryOptions(
    companyId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUniversityControllerGetPartnerMoasSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
  TError = unknown,
>(
  companyId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getUniversityControllerGetPartnerMoasQueryKey(companyId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>
  > = ({ signal }) => universityControllerGetPartnerMoas(companyId, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetPartnerMoasSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>
>;
export type UniversityControllerGetPartnerMoasSuspenseQueryError = unknown;

export function useUniversityControllerGetPartnerMoasSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
  TError = unknown,
>(
  companyId: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetPartnerMoasSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
  TError = unknown,
>(
  companyId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetPartnerMoasSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
  TError = unknown,
>(
  companyId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetPartnerMoasSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
  TError = unknown,
>(
  companyId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetPartnerMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getUniversityControllerGetPartnerMoasSuspenseQueryOptions(
      companyId,
      options,
    );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const universityControllerListPartners = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/partners`,
    method: "GET",
    signal,
  });
};

export const getUniversityControllerListPartnersQueryKey = () => {
  return [`/api/university/partners`] as const;
};

export const getUniversityControllerListPartnersQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerListPartners>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof universityControllerListPartners>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerListPartnersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerListPartners>>
  > = ({ signal }) => universityControllerListPartners(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof universityControllerListPartners>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerListPartnersQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerListPartners>>
>;
export type UniversityControllerListPartnersQueryError = unknown;

export function useUniversityControllerListPartners<
  TData = Awaited<ReturnType<typeof universityControllerListPartners>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListPartners>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerListPartners>>,
          TError,
          Awaited<ReturnType<typeof universityControllerListPartners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerListPartners<
  TData = Awaited<ReturnType<typeof universityControllerListPartners>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListPartners>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerListPartners>>,
          TError,
          Awaited<ReturnType<typeof universityControllerListPartners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerListPartners<
  TData = Awaited<ReturnType<typeof universityControllerListPartners>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerListPartners<
  TData = Awaited<ReturnType<typeof universityControllerListPartners>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUniversityControllerListPartnersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUniversityControllerListPartnersSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerListPartners>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof universityControllerListPartners>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerListPartnersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerListPartners>>
  > = ({ signal }) => universityControllerListPartners(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof universityControllerListPartners>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerListPartnersSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerListPartners>>
>;
export type UniversityControllerListPartnersSuspenseQueryError = unknown;

export function useUniversityControllerListPartnersSuspense<
  TData = Awaited<ReturnType<typeof universityControllerListPartners>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerListPartnersSuspense<
  TData = Awaited<ReturnType<typeof universityControllerListPartners>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerListPartnersSuspense<
  TData = Awaited<ReturnType<typeof universityControllerListPartners>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerListPartnersSuspense<
  TData = Awaited<ReturnType<typeof universityControllerListPartners>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getUniversityControllerListPartnersSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const universityControllerGetBlacklist = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/blacklist`,
    method: "GET",
    signal,
  });
};

export const getUniversityControllerGetBlacklistQueryKey = () => {
  return [`/api/university/blacklist`] as const;
};

export const getUniversityControllerGetBlacklistQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerGetBlacklistQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetBlacklist>>
  > = ({ signal }) => universityControllerGetBlacklist(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetBlacklistQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetBlacklist>>
>;
export type UniversityControllerGetBlacklistQueryError = unknown;

export function useUniversityControllerGetBlacklist<
  TData = Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetBlacklist>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetBlacklist<
  TData = Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetBlacklist>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetBlacklist<
  TData = Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetBlacklist<
  TData = Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUniversityControllerGetBlacklistQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUniversityControllerGetBlacklistSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerGetBlacklistQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetBlacklist>>
  > = ({ signal }) => universityControllerGetBlacklist(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetBlacklistSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetBlacklist>>
>;
export type UniversityControllerGetBlacklistSuspenseQueryError = unknown;

export function useUniversityControllerGetBlacklistSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetBlacklistSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetBlacklistSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetBlacklistSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetBlacklist>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getUniversityControllerGetBlacklistSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const universityControllerBlacklistCompany = (
  blacklistCompanyDto: BlacklistCompanyDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/blacklist`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: blacklistCompanyDto,
    signal,
  });
};

export const getUniversityControllerBlacklistCompanyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityControllerBlacklistCompany>>,
    TError,
    { data: BlacklistCompanyDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityControllerBlacklistCompany>>,
  TError,
  { data: BlacklistCompanyDto },
  TContext
> => {
  const mutationKey = ["universityControllerBlacklistCompany"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityControllerBlacklistCompany>>,
    { data: BlacklistCompanyDto }
  > = (props) => {
    const { data } = props ?? {};

    return universityControllerBlacklistCompany(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityControllerBlacklistCompanyMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerBlacklistCompany>>
>;
export type UniversityControllerBlacklistCompanyMutationBody =
  BlacklistCompanyDto;
export type UniversityControllerBlacklistCompanyMutationError = unknown;

export const useUniversityControllerBlacklistCompany = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityControllerBlacklistCompany>>,
      TError,
      { data: BlacklistCompanyDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityControllerBlacklistCompany>>,
  TError,
  { data: BlacklistCompanyDto },
  TContext
> => {
  const mutationOptions =
    getUniversityControllerBlacklistCompanyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityControllerUnblacklistCompany = (
  companyId: string | undefined | null,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/blacklist/${companyId}`,
    method: "DELETE",
  });
};

export const getUniversityControllerUnblacklistCompanyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityControllerUnblacklistCompany>>,
    TError,
    { companyId: string | undefined | null },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityControllerUnblacklistCompany>>,
  TError,
  { companyId: string | undefined | null },
  TContext
> => {
  const mutationKey = ["universityControllerUnblacklistCompany"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityControllerUnblacklistCompany>>,
    { companyId: string | undefined | null }
  > = (props) => {
    const { companyId } = props ?? {};

    return universityControllerUnblacklistCompany(companyId);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityControllerUnblacklistCompanyMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerUnblacklistCompany>>
>;

export type UniversityControllerUnblacklistCompanyMutationError = unknown;

export const useUniversityControllerUnblacklistCompany = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityControllerUnblacklistCompany>>,
      TError,
      { companyId: string | undefined | null },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityControllerUnblacklistCompany>>,
  TError,
  { companyId: string | undefined | null },
  TContext
> => {
  const mutationOptions =
    getUniversityControllerUnblacklistCompanyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityControllerGetAuditLog = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/audit`,
    method: "GET",
    signal,
  });
};

export const getUniversityControllerGetAuditLogQueryKey = () => {
  return [`/api/university/audit`] as const;
};

export const getUniversityControllerGetAuditLogQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerGetAuditLogQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetAuditLog>>
  > = ({ signal }) => universityControllerGetAuditLog(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetAuditLogQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetAuditLog>>
>;
export type UniversityControllerGetAuditLogQueryError = unknown;

export function useUniversityControllerGetAuditLog<
  TData = Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetAuditLog>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetAuditLog<
  TData = Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetAuditLog>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetAuditLog<
  TData = Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetAuditLog<
  TData = Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUniversityControllerGetAuditLogQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUniversityControllerGetAuditLogSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerGetAuditLogQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetAuditLog>>
  > = ({ signal }) => universityControllerGetAuditLog(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetAuditLogSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetAuditLog>>
>;
export type UniversityControllerGetAuditLogSuspenseQueryError = unknown;

export function useUniversityControllerGetAuditLogSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetAuditLogSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetAuditLogSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetAuditLogSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAuditLog>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getUniversityControllerGetAuditLogSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const universityControllerListTemplates = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/templates`,
    method: "GET",
    signal,
  });
};

export const getUniversityControllerListTemplatesQueryKey = () => {
  return [`/api/university/templates`] as const;
};

export const getUniversityControllerListTemplatesQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerListTemplates>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof universityControllerListTemplates>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerListTemplatesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerListTemplates>>
  > = ({ signal }) => universityControllerListTemplates(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof universityControllerListTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerListTemplatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerListTemplates>>
>;
export type UniversityControllerListTemplatesQueryError = unknown;

export function useUniversityControllerListTemplates<
  TData = Awaited<ReturnType<typeof universityControllerListTemplates>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerListTemplates>>,
          TError,
          Awaited<ReturnType<typeof universityControllerListTemplates>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerListTemplates<
  TData = Awaited<ReturnType<typeof universityControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerListTemplates>>,
          TError,
          Awaited<ReturnType<typeof universityControllerListTemplates>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerListTemplates<
  TData = Awaited<ReturnType<typeof universityControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerListTemplates<
  TData = Awaited<ReturnType<typeof universityControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getUniversityControllerListTemplatesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUniversityControllerListTemplatesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerListTemplates>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof universityControllerListTemplates>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerListTemplatesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerListTemplates>>
  > = ({ signal }) => universityControllerListTemplates(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof universityControllerListTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerListTemplatesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerListTemplates>>
>;
export type UniversityControllerListTemplatesSuspenseQueryError = unknown;

export function useUniversityControllerListTemplatesSuspense<
  TData = Awaited<ReturnType<typeof universityControllerListTemplates>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerListTemplatesSuspense<
  TData = Awaited<ReturnType<typeof universityControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerListTemplatesSuspense<
  TData = Awaited<ReturnType<typeof universityControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerListTemplatesSuspense<
  TData = Awaited<ReturnType<typeof universityControllerListTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerListTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getUniversityControllerListTemplatesSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const universityControllerToggleTemplateOffer = (
  templateId: string | undefined | null,
  toggleTemplateOfferDto: ToggleTemplateOfferDto,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/templates/${templateId}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: toggleTemplateOfferDto,
  });
};

export const getUniversityControllerToggleTemplateOfferMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityControllerToggleTemplateOffer>>,
    TError,
    { templateId: string | undefined | null; data: ToggleTemplateOfferDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityControllerToggleTemplateOffer>>,
  TError,
  { templateId: string | undefined | null; data: ToggleTemplateOfferDto },
  TContext
> => {
  const mutationKey = ["universityControllerToggleTemplateOffer"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityControllerToggleTemplateOffer>>,
    { templateId: string | undefined | null; data: ToggleTemplateOfferDto }
  > = (props) => {
    const { templateId, data } = props ?? {};

    return universityControllerToggleTemplateOffer(templateId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityControllerToggleTemplateOfferMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerToggleTemplateOffer>>
>;
export type UniversityControllerToggleTemplateOfferMutationBody =
  ToggleTemplateOfferDto;
export type UniversityControllerToggleTemplateOfferMutationError = unknown;

export const useUniversityControllerToggleTemplateOffer = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityControllerToggleTemplateOffer>>,
      TError,
      { templateId: string | undefined | null; data: ToggleTemplateOfferDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityControllerToggleTemplateOffer>>,
  TError,
  { templateId: string | undefined | null; data: ToggleTemplateOfferDto },
  TContext
> => {
  const mutationOptions =
    getUniversityControllerToggleTemplateOfferMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityControllerGetAccounts = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/accounts`,
    method: "GET",
    signal,
  });
};

export const getUniversityControllerGetAccountsQueryKey = () => {
  return [`/api/university/accounts`] as const;
};

export const getUniversityControllerGetAccountsQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetAccounts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof universityControllerGetAccounts>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerGetAccountsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetAccounts>>
  > = ({ signal }) => universityControllerGetAccounts(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetAccounts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetAccountsQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetAccounts>>
>;
export type UniversityControllerGetAccountsQueryError = unknown;

export function useUniversityControllerGetAccounts<
  TData = Awaited<ReturnType<typeof universityControllerGetAccounts>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAccounts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetAccounts>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetAccounts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetAccounts<
  TData = Awaited<ReturnType<typeof universityControllerGetAccounts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAccounts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof universityControllerGetAccounts>>,
          TError,
          Awaited<ReturnType<typeof universityControllerGetAccounts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetAccounts<
  TData = Awaited<ReturnType<typeof universityControllerGetAccounts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAccounts>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetAccounts<
  TData = Awaited<ReturnType<typeof universityControllerGetAccounts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAccounts>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUniversityControllerGetAccountsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUniversityControllerGetAccountsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof universityControllerGetAccounts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof universityControllerGetAccounts>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUniversityControllerGetAccountsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof universityControllerGetAccounts>>
  > = ({ signal }) => universityControllerGetAccounts(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof universityControllerGetAccounts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UniversityControllerGetAccountsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerGetAccounts>>
>;
export type UniversityControllerGetAccountsSuspenseQueryError = unknown;

export function useUniversityControllerGetAccountsSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetAccounts>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAccounts>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetAccountsSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetAccounts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAccounts>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUniversityControllerGetAccountsSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetAccounts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAccounts>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUniversityControllerGetAccountsSuspense<
  TData = Awaited<ReturnType<typeof universityControllerGetAccounts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof universityControllerGetAccounts>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getUniversityControllerGetAccountsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const universityControllerCreateStaff = (
  createStaffAccountDto: CreateStaffAccountDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/accounts`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createStaffAccountDto,
    signal,
  });
};

export const getUniversityControllerCreateStaffMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityControllerCreateStaff>>,
    TError,
    { data: CreateStaffAccountDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityControllerCreateStaff>>,
  TError,
  { data: CreateStaffAccountDto },
  TContext
> => {
  const mutationKey = ["universityControllerCreateStaff"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityControllerCreateStaff>>,
    { data: CreateStaffAccountDto }
  > = (props) => {
    const { data } = props ?? {};

    return universityControllerCreateStaff(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityControllerCreateStaffMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerCreateStaff>>
>;
export type UniversityControllerCreateStaffMutationBody = CreateStaffAccountDto;
export type UniversityControllerCreateStaffMutationError = unknown;

export const useUniversityControllerCreateStaff = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityControllerCreateStaff>>,
      TError,
      { data: CreateStaffAccountDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityControllerCreateStaff>>,
  TError,
  { data: CreateStaffAccountDto },
  TContext
> => {
  const mutationOptions =
    getUniversityControllerCreateStaffMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityControllerUpdateStaff = (
  accountId: string | undefined | null,
  updateStaffAccountDto: UpdateStaffAccountDto,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/accounts/${accountId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: updateStaffAccountDto,
  });
};

export const getUniversityControllerUpdateStaffMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityControllerUpdateStaff>>,
    TError,
    { accountId: string | undefined | null; data: UpdateStaffAccountDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityControllerUpdateStaff>>,
  TError,
  { accountId: string | undefined | null; data: UpdateStaffAccountDto },
  TContext
> => {
  const mutationKey = ["universityControllerUpdateStaff"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityControllerUpdateStaff>>,
    { accountId: string | undefined | null; data: UpdateStaffAccountDto }
  > = (props) => {
    const { accountId, data } = props ?? {};

    return universityControllerUpdateStaff(accountId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityControllerUpdateStaffMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerUpdateStaff>>
>;
export type UniversityControllerUpdateStaffMutationBody = UpdateStaffAccountDto;
export type UniversityControllerUpdateStaffMutationError = unknown;

export const useUniversityControllerUpdateStaff = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityControllerUpdateStaff>>,
      TError,
      { accountId: string | undefined | null; data: UpdateStaffAccountDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityControllerUpdateStaff>>,
  TError,
  { accountId: string | undefined | null; data: UpdateStaffAccountDto },
  TContext
> => {
  const mutationOptions =
    getUniversityControllerUpdateStaffMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityControllerDeactivateStaff = (
  accountId: string | undefined | null,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/accounts/${accountId}/deactivate`,
    method: "PATCH",
  });
};

export const getUniversityControllerDeactivateStaffMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityControllerDeactivateStaff>>,
    TError,
    { accountId: string | undefined | null },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityControllerDeactivateStaff>>,
  TError,
  { accountId: string | undefined | null },
  TContext
> => {
  const mutationKey = ["universityControllerDeactivateStaff"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityControllerDeactivateStaff>>,
    { accountId: string | undefined | null }
  > = (props) => {
    const { accountId } = props ?? {};

    return universityControllerDeactivateStaff(accountId);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityControllerDeactivateStaffMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerDeactivateStaff>>
>;

export type UniversityControllerDeactivateStaffMutationError = unknown;

export const useUniversityControllerDeactivateStaff = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityControllerDeactivateStaff>>,
      TError,
      { accountId: string | undefined | null },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityControllerDeactivateStaff>>,
  TError,
  { accountId: string | undefined | null },
  TContext
> => {
  const mutationOptions =
    getUniversityControllerDeactivateStaffMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityControllerReactivateStaff = (
  accountId: string | undefined | null,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/accounts/${accountId}/reactivate`,
    method: "PATCH",
  });
};

export const getUniversityControllerReactivateStaffMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityControllerReactivateStaff>>,
    TError,
    { accountId: string | undefined | null },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityControllerReactivateStaff>>,
  TError,
  { accountId: string | undefined | null },
  TContext
> => {
  const mutationKey = ["universityControllerReactivateStaff"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityControllerReactivateStaff>>,
    { accountId: string | undefined | null }
  > = (props) => {
    const { accountId } = props ?? {};

    return universityControllerReactivateStaff(accountId);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityControllerReactivateStaffMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerReactivateStaff>>
>;

export type UniversityControllerReactivateStaffMutationError = unknown;

export const useUniversityControllerReactivateStaff = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityControllerReactivateStaff>>,
      TError,
      { accountId: string | undefined | null },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityControllerReactivateStaff>>,
  TError,
  { accountId: string | undefined | null },
  TContext
> => {
  const mutationOptions =
    getUniversityControllerReactivateStaffMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityControllerResendInvite = (
  accountId: string | undefined | null,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/university/accounts/${accountId}/resend-invite`,
    method: "POST",
    signal,
  });
};

export const getUniversityControllerResendInviteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityControllerResendInvite>>,
    TError,
    { accountId: string | undefined | null },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityControllerResendInvite>>,
  TError,
  { accountId: string | undefined | null },
  TContext
> => {
  const mutationKey = ["universityControllerResendInvite"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityControllerResendInvite>>,
    { accountId: string | undefined | null }
  > = (props) => {
    const { accountId } = props ?? {};

    return universityControllerResendInvite(accountId);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityControllerResendInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityControllerResendInvite>>
>;

export type UniversityControllerResendInviteMutationError = unknown;

export const useUniversityControllerResendInvite = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityControllerResendInvite>>,
      TError,
      { accountId: string | undefined | null },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityControllerResendInvite>>,
  TError,
  { accountId: string | undefined | null },
  TContext
> => {
  const mutationOptions =
    getUniversityControllerResendInviteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
