/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  CompanyForgotDto,
  CompanyLoginDto,
  CompanyOtpRequestDto,
  CompanyOtpVerifyDto,
  CompanyRegisterDto,
  CompanyResetDto,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const companyAuthControllerRegister = (
  companyRegisterDto: CompanyRegisterDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/auth/company/register`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyRegisterDto,
    signal,
  });
};

export const getCompanyAuthControllerRegisterMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerRegister>>,
    TError,
    { data: CompanyRegisterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerRegister>>,
  TError,
  { data: CompanyRegisterDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerRegister"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerRegister>>,
    { data: CompanyRegisterDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerRegister(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerRegister>>
>;
export type CompanyAuthControllerRegisterMutationBody = CompanyRegisterDto;
export type CompanyAuthControllerRegisterMutationError = unknown;

export const useCompanyAuthControllerRegister = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerRegister>>,
      TError,
      { data: CompanyRegisterDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerRegister>>,
  TError,
  { data: CompanyRegisterDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerOtpRequest = (
  companyOtpRequestDto: CompanyOtpRequestDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/auth/company/otp/request`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyOtpRequestDto,
    signal,
  });
};

export const getCompanyAuthControllerOtpRequestMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
    TError,
    { data: CompanyOtpRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
  TError,
  { data: CompanyOtpRequestDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerOtpRequest"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
    { data: CompanyOtpRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerOtpRequest(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerOtpRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>
>;
export type CompanyAuthControllerOtpRequestMutationBody = CompanyOtpRequestDto;
export type CompanyAuthControllerOtpRequestMutationError = unknown;

export const useCompanyAuthControllerOtpRequest = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
      TError,
      { data: CompanyOtpRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
  TError,
  { data: CompanyOtpRequestDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerOtpRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerOtpVerify = (
  companyOtpVerifyDto: CompanyOtpVerifyDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/auth/company/otp/verify`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyOtpVerifyDto,
    signal,
  });
};

export const getCompanyAuthControllerOtpVerifyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
    TError,
    { data: CompanyOtpVerifyDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
  TError,
  { data: CompanyOtpVerifyDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerOtpVerify"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
    { data: CompanyOtpVerifyDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerOtpVerify(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerOtpVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>
>;
export type CompanyAuthControllerOtpVerifyMutationBody = CompanyOtpVerifyDto;
export type CompanyAuthControllerOtpVerifyMutationError = unknown;

export const useCompanyAuthControllerOtpVerify = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
      TError,
      { data: CompanyOtpVerifyDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
  TError,
  { data: CompanyOtpVerifyDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerOtpVerifyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerLogin = (
  companyLoginDto: CompanyLoginDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/auth/company/login`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyLoginDto,
    signal,
  });
};

export const getCompanyAuthControllerLoginMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerLogin>>,
    TError,
    { data: CompanyLoginDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerLogin>>,
  TError,
  { data: CompanyLoginDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerLogin"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerLogin>>,
    { data: CompanyLoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerLogin>>
>;
export type CompanyAuthControllerLoginMutationBody = CompanyLoginDto;
export type CompanyAuthControllerLoginMutationError = unknown;

export const useCompanyAuthControllerLogin = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerLogin>>,
      TError,
      { data: CompanyLoginDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerLogin>>,
  TError,
  { data: CompanyLoginDto },
  TContext
> => {
  const mutationOptions = getCompanyAuthControllerLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerLogout = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/auth/company/logout`,
    method: "POST",
    signal,
  });
};

export const getCompanyAuthControllerLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["companyAuthControllerLogout"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerLogout>>,
    void
  > = () => {
    return companyAuthControllerLogout();
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerLogout>>
>;

export type CompanyAuthControllerLogoutMutationError = unknown;

export const useCompanyAuthControllerLogout = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerLogout>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerForgot = (
  companyForgotDto: CompanyForgotDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/auth/company/forgot`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyForgotDto,
    signal,
  });
};

export const getCompanyAuthControllerForgotMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerForgot>>,
    TError,
    { data: CompanyForgotDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerForgot>>,
  TError,
  { data: CompanyForgotDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerForgot"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerForgot>>,
    { data: CompanyForgotDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerForgot(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerForgotMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerForgot>>
>;
export type CompanyAuthControllerForgotMutationBody = CompanyForgotDto;
export type CompanyAuthControllerForgotMutationError = unknown;

export const useCompanyAuthControllerForgot = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerForgot>>,
      TError,
      { data: CompanyForgotDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerForgot>>,
  TError,
  { data: CompanyForgotDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerForgotMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerReset = (
  companyResetDto: CompanyResetDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<void>({
    url: `/api/auth/company/reset`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyResetDto,
    signal,
  });
};

export const getCompanyAuthControllerResetMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerReset>>,
    TError,
    { data: CompanyResetDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerReset>>,
  TError,
  { data: CompanyResetDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerReset"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerReset>>,
    { data: CompanyResetDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerReset(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerResetMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerReset>>
>;
export type CompanyAuthControllerResetMutationBody = CompanyResetDto;
export type CompanyAuthControllerResetMutationError = unknown;

export const useCompanyAuthControllerReset = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerReset>>,
      TError,
      { data: CompanyResetDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerReset>>,
  TError,
  { data: CompanyResetDto },
  TContext
> => {
  const mutationOptions = getCompanyAuthControllerResetMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
