/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  BaseResponse,
  CompanyLoginInviteResponse,
  CompanyLoginOtpRequestDto,
  CompanyLoginOtpVerifyDto,
  CompanyOtpRequestDto,
  CompanyOtpRequestResponse,
  CompanyOtpVerifyDto,
  CompanyOtpVerifyResponse,
  CompanyRegisterDto,
  CompanyRegisterInvitedResponse,
  CompanyRegisterResponse,
  ErrorResponse,
  LoginViaInviteDto,
  RegisterInvitedCompanyDto,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const companyAuthControllerRegister = (
  companyRegisterDto: CompanyRegisterDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyRegisterResponse>({
    url: `/api/auth/company/register`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyRegisterDto,
    signal,
  });
};

export const getCompanyAuthControllerRegisterMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerRegister>>,
    TError,
    { data: CompanyRegisterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerRegister>>,
  TError,
  { data: CompanyRegisterDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerRegister"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerRegister>>,
    { data: CompanyRegisterDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerRegister(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerRegister>>
>;
export type CompanyAuthControllerRegisterMutationBody = CompanyRegisterDto;
export type CompanyAuthControllerRegisterMutationError = ErrorResponse;

export const useCompanyAuthControllerRegister = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerRegister>>,
      TError,
      { data: CompanyRegisterDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerRegister>>,
  TError,
  { data: CompanyRegisterDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerOtpRequest = (
  companyOtpRequestDto: CompanyOtpRequestDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyOtpRequestResponse>({
    url: `/api/auth/company/otp/request`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyOtpRequestDto,
    signal,
  });
};

export const getCompanyAuthControllerOtpRequestMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
    TError,
    { data: CompanyOtpRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
  TError,
  { data: CompanyOtpRequestDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerOtpRequest"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
    { data: CompanyOtpRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerOtpRequest(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerOtpRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>
>;
export type CompanyAuthControllerOtpRequestMutationBody = CompanyOtpRequestDto;
export type CompanyAuthControllerOtpRequestMutationError = ErrorResponse;

export const useCompanyAuthControllerOtpRequest = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
      TError,
      { data: CompanyOtpRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
  TError,
  { data: CompanyOtpRequestDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerOtpRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerOtpVerify = (
  companyOtpVerifyDto: CompanyOtpVerifyDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyOtpVerifyResponse>({
    url: `/api/auth/company/otp/verify`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyOtpVerifyDto,
    signal,
  });
};

export const getCompanyAuthControllerOtpVerifyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
    TError,
    { data: CompanyOtpVerifyDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
  TError,
  { data: CompanyOtpVerifyDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerOtpVerify"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
    { data: CompanyOtpVerifyDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerOtpVerify(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerOtpVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>
>;
export type CompanyAuthControllerOtpVerifyMutationBody = CompanyOtpVerifyDto;
export type CompanyAuthControllerOtpVerifyMutationError = ErrorResponse;

export const useCompanyAuthControllerOtpVerify = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
      TError,
      { data: CompanyOtpVerifyDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
  TError,
  { data: CompanyOtpVerifyDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerOtpVerifyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerLoginOtpRequest = (
  companyLoginOtpRequestDto: CompanyLoginOtpRequestDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyOtpRequestResponse>({
    url: `/api/auth/company/login/otp/request`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyLoginOtpRequestDto,
    signal,
  });
};

export const getCompanyAuthControllerLoginOtpRequestMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerLoginOtpRequest>>,
    TError,
    { data: CompanyLoginOtpRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerLoginOtpRequest>>,
  TError,
  { data: CompanyLoginOtpRequestDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerLoginOtpRequest"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerLoginOtpRequest>>,
    { data: CompanyLoginOtpRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerLoginOtpRequest(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerLoginOtpRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerLoginOtpRequest>>
>;
export type CompanyAuthControllerLoginOtpRequestMutationBody =
  CompanyLoginOtpRequestDto;
export type CompanyAuthControllerLoginOtpRequestMutationError = ErrorResponse;

export const useCompanyAuthControllerLoginOtpRequest = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerLoginOtpRequest>>,
      TError,
      { data: CompanyLoginOtpRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerLoginOtpRequest>>,
  TError,
  { data: CompanyLoginOtpRequestDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerLoginOtpRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerLoginOtpVerify = (
  companyLoginOtpVerifyDto: CompanyLoginOtpVerifyDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/company/login/otp/verify`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyLoginOtpVerifyDto,
    signal,
  });
};

export const getCompanyAuthControllerLoginOtpVerifyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerLoginOtpVerify>>,
    TError,
    { data: CompanyLoginOtpVerifyDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerLoginOtpVerify>>,
  TError,
  { data: CompanyLoginOtpVerifyDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerLoginOtpVerify"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerLoginOtpVerify>>,
    { data: CompanyLoginOtpVerifyDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerLoginOtpVerify(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerLoginOtpVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerLoginOtpVerify>>
>;
export type CompanyAuthControllerLoginOtpVerifyMutationBody =
  CompanyLoginOtpVerifyDto;
export type CompanyAuthControllerLoginOtpVerifyMutationError = ErrorResponse;

export const useCompanyAuthControllerLoginOtpVerify = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerLoginOtpVerify>>,
      TError,
      { data: CompanyLoginOtpVerifyDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerLoginOtpVerify>>,
  TError,
  { data: CompanyLoginOtpVerifyDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerLoginOtpVerifyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerLogout = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/company/logout`,
    method: "POST",
    signal,
  });
};

export const getCompanyAuthControllerLogoutMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["companyAuthControllerLogout"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerLogout>>,
    void
  > = () => {
    return companyAuthControllerLogout();
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerLogout>>
>;

export type CompanyAuthControllerLogoutMutationError = ErrorResponse;

export const useCompanyAuthControllerLogout = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerLogout>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerRegisterInvited = (
  registerInvitedCompanyDto: RegisterInvitedCompanyDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyRegisterInvitedResponse>({
    url: `/api/auth/company/register-invited`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: registerInvitedCompanyDto,
    signal,
  });
};

export const getCompanyAuthControllerRegisterInvitedMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>,
    TError,
    { data: RegisterInvitedCompanyDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>,
  TError,
  { data: RegisterInvitedCompanyDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerRegisterInvited"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>,
    { data: RegisterInvitedCompanyDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerRegisterInvited(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerRegisterInvitedMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>
>;
export type CompanyAuthControllerRegisterInvitedMutationBody =
  RegisterInvitedCompanyDto;
export type CompanyAuthControllerRegisterInvitedMutationError = ErrorResponse;

export const useCompanyAuthControllerRegisterInvited = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>,
      TError,
      { data: RegisterInvitedCompanyDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>,
  TError,
  { data: RegisterInvitedCompanyDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerRegisterInvitedMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerLoginViaInvite = (
  loginViaInviteDto: LoginViaInviteDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyLoginInviteResponse>({
    url: `/api/auth/company/login-invite`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: loginViaInviteDto,
    signal,
  });
};

export const getCompanyAuthControllerLoginViaInviteMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>,
    TError,
    { data: LoginViaInviteDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>,
  TError,
  { data: LoginViaInviteDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerLoginViaInvite"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>,
    { data: LoginViaInviteDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerLoginViaInvite(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerLoginViaInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>
>;
export type CompanyAuthControllerLoginViaInviteMutationBody = LoginViaInviteDto;
export type CompanyAuthControllerLoginViaInviteMutationError = ErrorResponse;

export const useCompanyAuthControllerLoginViaInvite = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>,
      TError,
      { data: LoginViaInviteDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>,
  TError,
  { data: LoginViaInviteDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerLoginViaInviteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
