/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  ApplyRevokeTokenDto,
  BaseResponse,
  ErrorResponse,
  RevokeTokenResolvedResponse,
  SignControllerSubmitBody,
  SignTokenResolvedResponse,
  SubmitSignatureResponse,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const signControllerResolve = (
  token: string | undefined | null,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<SignTokenResolvedResponse>({
    url: `/api/sign/${token}`,
    method: "GET",
    signal,
  });
};

export const getSignControllerResolveQueryKey = (
  token?: string | undefined | null,
) => {
  return [`/api/sign/${token}`] as const;
};

export const getSignControllerResolveQueryOptions = <
  TData = Awaited<ReturnType<typeof signControllerResolve>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolve>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignControllerResolveQueryKey(token);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signControllerResolve>>
  > = ({ signal }) => signControllerResolve(token, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!token,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof signControllerResolve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignControllerResolveQueryResult = NonNullable<
  Awaited<ReturnType<typeof signControllerResolve>>
>;
export type SignControllerResolveQueryError = ErrorResponse;

export function useSignControllerResolve<
  TData = Awaited<ReturnType<typeof signControllerResolve>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signControllerResolve>>,
          TError,
          Awaited<ReturnType<typeof signControllerResolve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSignControllerResolve<
  TData = Awaited<ReturnType<typeof signControllerResolve>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signControllerResolve>>,
          TError,
          Awaited<ReturnType<typeof signControllerResolve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSignControllerResolve<
  TData = Awaited<ReturnType<typeof signControllerResolve>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSignControllerResolve<
  TData = Awaited<ReturnType<typeof signControllerResolve>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSignControllerResolveQueryOptions(token, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSignControllerResolveSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof signControllerResolve>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolve>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignControllerResolveQueryKey(token);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signControllerResolve>>
  > = ({ signal }) => signControllerResolve(token, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof signControllerResolve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignControllerResolveSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof signControllerResolve>>
>;
export type SignControllerResolveSuspenseQueryError = ErrorResponse;

export function useSignControllerResolveSuspense<
  TData = Awaited<ReturnType<typeof signControllerResolve>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSignControllerResolveSuspense<
  TData = Awaited<ReturnType<typeof signControllerResolve>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSignControllerResolveSuspense<
  TData = Awaited<ReturnType<typeof signControllerResolve>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSignControllerResolveSuspense<
  TData = Awaited<ReturnType<typeof signControllerResolve>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSignControllerResolveSuspenseQueryOptions(
    token,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const signControllerSubmit = (
  token: string | undefined | null,
  signControllerSubmitBody: SignControllerSubmitBody,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`name`, signControllerSubmitBody.name);
  formData.append(`title`, signControllerSubmitBody.title);
  if (signControllerSubmitBody.signatureText !== undefined) {
    formData.append(`signatureText`, signControllerSubmitBody.signatureText);
  }
  formData.append(`autoSign`, signControllerSubmitBody.autoSign.toString());
  if (signControllerSubmitBody.signature !== undefined) {
    formData.append(`signature`, signControllerSubmitBody.signature);
  }

  return preconfiguredAxiosFunction<SubmitSignatureResponse>({
    url: `/api/sign/${token}`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    signal,
  });
};

export const getSignControllerSubmitMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signControllerSubmit>>,
    TError,
    { token: string | undefined | null; data: SignControllerSubmitBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signControllerSubmit>>,
  TError,
  { token: string | undefined | null; data: SignControllerSubmitBody },
  TContext
> => {
  const mutationKey = ["signControllerSubmit"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signControllerSubmit>>,
    { token: string | undefined | null; data: SignControllerSubmitBody }
  > = (props) => {
    const { token, data } = props ?? {};

    return signControllerSubmit(token, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignControllerSubmitMutationResult = NonNullable<
  Awaited<ReturnType<typeof signControllerSubmit>>
>;
export type SignControllerSubmitMutationBody = SignControllerSubmitBody;
export type SignControllerSubmitMutationError = ErrorResponse;

export const useSignControllerSubmit = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signControllerSubmit>>,
      TError,
      { token: string | undefined | null; data: SignControllerSubmitBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof signControllerSubmit>>,
  TError,
  { token: string | undefined | null; data: SignControllerSubmitBody },
  TContext
> => {
  const mutationOptions = getSignControllerSubmitMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const signControllerResolveRevoke = (
  token: string | undefined | null,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<RevokeTokenResolvedResponse>({
    url: `/api/sign/revoke/${token}/resolve`,
    method: "GET",
    signal,
  });
};

export const getSignControllerResolveRevokeQueryKey = (
  token?: string | undefined | null,
) => {
  return [`/api/sign/revoke/${token}/resolve`] as const;
};

export const getSignControllerResolveRevokeQueryOptions = <
  TData = Awaited<ReturnType<typeof signControllerResolveRevoke>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolveRevoke>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignControllerResolveRevokeQueryKey(token);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signControllerResolveRevoke>>
  > = ({ signal }) => signControllerResolveRevoke(token, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!token,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof signControllerResolveRevoke>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignControllerResolveRevokeQueryResult = NonNullable<
  Awaited<ReturnType<typeof signControllerResolveRevoke>>
>;
export type SignControllerResolveRevokeQueryError = ErrorResponse;

export function useSignControllerResolveRevoke<
  TData = Awaited<ReturnType<typeof signControllerResolveRevoke>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolveRevoke>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signControllerResolveRevoke>>,
          TError,
          Awaited<ReturnType<typeof signControllerResolveRevoke>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSignControllerResolveRevoke<
  TData = Awaited<ReturnType<typeof signControllerResolveRevoke>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolveRevoke>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signControllerResolveRevoke>>,
          TError,
          Awaited<ReturnType<typeof signControllerResolveRevoke>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSignControllerResolveRevoke<
  TData = Awaited<ReturnType<typeof signControllerResolveRevoke>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolveRevoke>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSignControllerResolveRevoke<
  TData = Awaited<ReturnType<typeof signControllerResolveRevoke>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolveRevoke>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSignControllerResolveRevokeQueryOptions(
    token,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSignControllerResolveRevokeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof signControllerResolveRevoke>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolveRevoke>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignControllerResolveRevokeQueryKey(token);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signControllerResolveRevoke>>
  > = ({ signal }) => signControllerResolveRevoke(token, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof signControllerResolveRevoke>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignControllerResolveRevokeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof signControllerResolveRevoke>>
>;
export type SignControllerResolveRevokeSuspenseQueryError = ErrorResponse;

export function useSignControllerResolveRevokeSuspense<
  TData = Awaited<ReturnType<typeof signControllerResolveRevoke>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolveRevoke>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSignControllerResolveRevokeSuspense<
  TData = Awaited<ReturnType<typeof signControllerResolveRevoke>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolveRevoke>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSignControllerResolveRevokeSuspense<
  TData = Awaited<ReturnType<typeof signControllerResolveRevoke>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolveRevoke>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSignControllerResolveRevokeSuspense<
  TData = Awaited<ReturnType<typeof signControllerResolveRevoke>>,
  TError = ErrorResponse,
>(
  token: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signControllerResolveRevoke>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSignControllerResolveRevokeSuspenseQueryOptions(
    token,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const signControllerRevoke = (
  token: string | undefined | null,
  applyRevokeTokenDto: ApplyRevokeTokenDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/sign/revoke/${token}`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: applyRevokeTokenDto,
    signal,
  });
};

export const getSignControllerRevokeMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signControllerRevoke>>,
    TError,
    { token: string | undefined | null; data: ApplyRevokeTokenDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signControllerRevoke>>,
  TError,
  { token: string | undefined | null; data: ApplyRevokeTokenDto },
  TContext
> => {
  const mutationKey = ["signControllerRevoke"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signControllerRevoke>>,
    { token: string | undefined | null; data: ApplyRevokeTokenDto }
  > = (props) => {
    const { token, data } = props ?? {};

    return signControllerRevoke(token, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignControllerRevokeMutationResult = NonNullable<
  Awaited<ReturnType<typeof signControllerRevoke>>
>;
export type SignControllerRevokeMutationBody = ApplyRevokeTokenDto;
export type SignControllerRevokeMutationError = ErrorResponse;

export const useSignControllerRevoke = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signControllerRevoke>>,
      TError,
      { token: string | undefined | null; data: ApplyRevokeTokenDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof signControllerRevoke>>,
  TError,
  { token: string | undefined | null; data: ApplyRevokeTokenDto },
  TContext
> => {
  const mutationOptions = getSignControllerRevokeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
